#!/usr/bin/env python3
"""
Mock MATLAB simulator for demo pipeline.

Parses the -batch command string and fakes the appropriate operation:
  - test_<algo>: reads test vectors, writes matlab_outputs.json using expected values
  - codegen_config: writes pre-built C++ to the generated directory
"""

import json
import os
import re
import sys
import glob


def handle_test(batch_code):
    """Fake MATLAB test harness: read test vectors, write matlab_outputs.json."""
    # Parse: results = test_kalman_filter('vectors_dir', 'results_dir');
    m = re.search(r"test_\w+\(\s*'([^']+)'\s*,\s*'([^']+)'\s*\)", batch_code)
    if not m:
        print("Mock MATLAB: could not parse test command", file=sys.stderr)
        return 1

    vectors_dir = m.group(1)
    results_dir = m.group(2)

    print(f"Mock MATLAB: running test harness")
    print(f"  Vectors dir: {vectors_dir}")
    print(f"  Results dir: {results_dir}")

    os.makedirs(results_dir, exist_ok=True)

    outputs = []
    total = 0
    for vector_file in sorted(glob.glob(os.path.join(vectors_dir, "*.json"))):
        if "schema" in os.path.basename(vector_file):
            continue
        with open(vector_file) as f:
            data = json.load(f)

        global_tol = 1e-10
        if "global_tolerance" in data and "absolute" in data["global_tolerance"]:
            global_tol = data["global_tolerance"]["absolute"]

        for tc in data.get("test_cases", []):
            total += 1
            name = tc["name"]
            expected = tc["expected_output"]

            # Use expected output as "actual" (mock produces perfect results)
            tol = global_tol
            if "tolerance" in tc and "absolute" in tc["tolerance"]:
                tol = tc["tolerance"]["absolute"]

            outputs.append({
                "test_name": name,
                "actual_state": expected["updated_state"],
                "actual_covariance": expected["updated_covariance"],
                "tolerance": tol,
            })
            print(f"  PASS: {name}")

    # Write matlab_outputs.json
    output_path = os.path.join(results_dir, "matlab_outputs.json")
    with open(output_path, "w") as f:
        json.dump(outputs, f, indent=2)

    print(f"MATLAB tests PASSED: {total} of {total}")
    return 0


def handle_codegen(batch_code):
    """Fake MATLAB Coder: write pre-built C++ to the generated directory."""
    # Parse: codegen_config('gen_dir');
    m = re.search(r"codegen_config\(\s*'([^']+)'\s*\)", batch_code)
    if not m:
        print("Mock MATLAB: could not parse codegen command", file=sys.stderr)
        return 1

    gen_dir = m.group(1)

    print(f"Mock MATLAB: running code generation")
    print(f"  Output dir: {gen_dir}")

    os.makedirs(gen_dir, exist_ok=True)

    # Write header
    header_path = os.path.join(gen_dir, "kalman_filter.h")
    with open(header_path, "w") as f:
        f.write(KALMAN_FILTER_H)
    print(f"  Generated: kalman_filter.h")

    # Write implementation
    cpp_path = os.path.join(gen_dir, "kalman_filter.cpp")
    with open(cpp_path, "w") as f:
        f.write(KALMAN_FILTER_CPP)
    print(f"  Generated: kalman_filter.cpp")

    # Extract algorithm name from batch code
    algo_m = re.search(r"for\s+(\w+)", batch_code)
    algo = algo_m.group(1) if algo_m else "kalman_filter"
    print(f"Code generation succeeded for {algo}")
    return 0


# ---------------------------------------------------------------------------
# Embedded C++ templates (identical to algorithms/kalman_filter/generated/)
# ---------------------------------------------------------------------------

KALMAN_FILTER_H = r"""#ifndef KALMAN_FILTER_H
#define KALMAN_FILTER_H

// Auto-generated by MATLAB Coder (mock)

namespace kalman_filter {

void kalman_filter(
    const double state[2],
    double measurement,
    const double state_covariance[4],
    double measurement_noise,
    double process_noise,
    double updated_state[2],
    double updated_covariance[4]);

} // namespace kalman_filter

#endif // KALMAN_FILTER_H
"""

KALMAN_FILTER_CPP = r"""#include "kalman_filter.h"

namespace kalman_filter {

void kalman_filter(
    const double state[2],
    double measurement,
    const double state_covariance[4],
    double measurement_noise,
    double process_noise,
    double updated_state[2],
    double updated_covariance[4])
{
    double P11 = state_covariance[0];
    double P12 = state_covariance[1];
    double P21 = state_covariance[2];
    double P22 = state_covariance[3];

    // --- Predict (constant velocity, dt=1) ---
    double x_pred0 = state[0] + state[1];
    double x_pred1 = state[1];

    double Pp11 = (P11 + P21) + (P12 + P22) + process_noise;
    double Pp12 = (P12 + P22);
    double Pp21 = (P21 + P22);
    double Pp22 = P22 + process_noise;

    // --- Update ---
    double y = measurement - x_pred0;
    double S = Pp11 + measurement_noise;

    double K0 = Pp11 / S;
    double K1 = Pp21 / S;

    updated_state[0] = x_pred0 + K0 * y;
    updated_state[1] = x_pred1 + K1 * y;

    // Joseph form covariance update
    double ikh00 = 1.0 - K0;
    double ikh10 = -K1;

    double A00 = ikh00 * Pp11;
    double A01 = ikh00 * Pp12;
    double A10 = ikh10 * Pp11 + Pp21;
    double A11 = ikh10 * Pp12 + Pp22;

    double P_up11 = A00 * ikh00 + A01 * ikh10;
    double P_up12 = A01;
    double P_up21 = A10 * ikh00 + A11 * ikh10;
    double P_up22 = A11;

    P_up11 += K0 * measurement_noise * K0;
    P_up12 += K0 * measurement_noise * K1;
    P_up21 += K1 * measurement_noise * K0;
    P_up22 += K1 * measurement_noise * K1;

    updated_covariance[0] = P_up11;
    updated_covariance[1] = P_up12;
    updated_covariance[2] = P_up21;
    updated_covariance[3] = P_up22;
}

} // namespace kalman_filter
"""


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Mock MATLAB: no batch code provided", file=sys.stderr)
        sys.exit(1)

    batch_code = sys.argv[1]

    if "test_" in batch_code:
        sys.exit(handle_test(batch_code))
    elif "codegen_config" in batch_code:
        sys.exit(handle_codegen(batch_code))
    else:
        # Unknown command — just succeed silently
        print(f"Mock MATLAB: unrecognized command, returning success")
        sys.exit(0)


if __name__ == "__main__":
    main()
